config/routes.rb
Rails.application.routes.draw do

  root :to => 'pharmaceutical_masters#index'
  resources :pharmaceutical_masters do
    collection do
      post :integrate
      get :export_csv
      delete :delete_all
    end
  end
  resources :regulation_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :efficacy_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :gs1_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :hot_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :price_masters do
    collection do
      post :input
      delete :delete_all
    end
  end

end

app/models/regulation_master.rb
require 'csv'
class RegulationMaster < ActiveRecord::Base
  # self.primary_key = "code"
  has_one :price_master, :primary_key => "code", :foreign_key => "ad"

  def self.input(file)
    RegulationMaster.transaction do
      delete_all
      imported_num = 0
      regulation_master_list = []

      open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
        csv = CSV.new(f, :headers => :first_row)
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          regulation_master = new
          regulation_master.attributes = table.to_hash.slice(
              *table.to_hash.except(:code, :name, :created_at, :updated_at).keys)

          if regulation_master.valid?
            regulation_master_list << regulation_master
            imported_num += 1
          end
        end
      end
      RegulationMaster.import regulation_master_list
      imported_num
    end
  rescue => e
    p  e.message
  end

end

app/controllers/regulation_masters_controller.rb
class RegulationMastersController < ApplicationController
  before_action :set_regulation_master, only: [:show, :edit, :update, :destroy]

  def input
    if params[:csv_file].blank?
      redirect_to(regulation_masters_url, alert: INPUT_BLANK_ALERT)
    elsif params[:csv_file].original_filename.eql?('regulation_master.csv')
      num = RegulationMaster.input(params[:csv_file])
      redirect_to(regulation_masters_url, notice: "#{num.to_s}" + INPUT_NOTICE)
    else
      redirect_to(regulation_masters_url, alert: INPUT_DIFFERENT_ALERT)
    end
  end

  def delete_all
    RegulationMaster.delete_all
    respond_to do |format|
      format.html { redirect_to regulation_masters_url, notice: DELETE_ALL_NOTICE }
      format.json { head :no_content }
    end
  end
  
  # GET /regulation_masters
  # GET /regulation_masters.json
  def index
    @regulation_masters = RegulationMaster.page(params[:page])
    # @regulation_masters = RegulationMaster.all
  end

  # GET /regulation_masters/1
  # GET /regulation_masters/1.json
  def show
  end

  # GET /regulation_masters/new
  def new
    @regulation_master = RegulationMaster.new
  end

  # GET /regulation_masters/1/edit
  def edit
  end

  # POST /regulation_masters
  # POST /regulation_masters.json
  def create
    @regulation_master = RegulationMaster.new(regulation_master_params)

    respond_to do |format|
      if @regulation_master.save
        format.html { redirect_to @regulation_master, notice: CREATE_NOTICE }
        format.json { render :show, status: :created, location: @regulation_master }
      else
        format.html { render :new }
        format.json { render json: @regulation_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regulation_masters/1
  # PATCH/PUT /regulation_masters/1.json
  def update
    respond_to do |format|
      if @regulation_master.update(regulation_master_params)
        format.html { redirect_to @regulation_master, notice: UPDATE_NOTICE }
        format.json { render :show, status: :ok, location: @regulation_master }
      else
        format.html { render :edit }
        format.json { render json: @regulation_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regulation_masters/1
  # DELETE /regulation_masters/1.json
  def destroy
    @regulation_master.destroy
    respond_to do |format|
      format.html { redirect_to regulation_masters_url, notice: DELETE_NOTICE }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regulation_master
      @regulation_master = RegulationMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regulation_master_params
      params.require(:regulation_master).permit(:code, :name)
    end
end

app/helpers/regulation_masters_helper.rb
module RegulationMastersHelper
end

app/views/regulation_masters/_form.html.erb
<%= form_for(@regulation_master) do |f| %>
  <% if @regulation_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regulation_master.errors.count, "error") %> prohibited this regulation_master from being saved:</h2>

      <ul>
      <% @regulation_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regulation_masters/edit.html.erb
<h1>Editing Regulation Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @regulation_master %> |
<%= link_to 'Back', regulation_masters_path %>

app/views/regulation_masters/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Regulation Masters</h1>
    <p>This is 規制分類マスタ</p>
    <p>規制分類表：(4) 医薬品マスター > 14 は<u><%= link_to "こちら", "http://www.iryohoken.go.jp/shinryohoshu/file/spec/22rec.pdf" %></u></p>
    <p>regulation_master.csv に名前変更してください</p>

    <p class="text-danger"><strong><%= flash[:alert] %></strong></p>
    <p class="text-success"><strong><%= flash[:notice] %></strong></p>

    <div class="container">
      <p>
        <%= form_tag(input_regulation_masters_path, :method => :post, multipart: true) do %>
            <%= file_field_tag :csv_file %>
            <%= submit_tag "CSVインポート", :class => "btn btn-primary btn-raised" %>
        <% end %>
        <%= link_to '新規登録', new_regulation_master_path, class: "btn btn-primary btn-raised"  %>
        <%= link_to '全削除', delete_all_regulation_masters_path, :method => :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-raised"  %>
      </p>
    </div>
  </div>
</div>

<p><%= page_entries_info @regulation_masters %></p>
<p><%= paginate @regulation_masters %></p>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>規制分類コード</th>
    <th>規制分類名</th>
    <th>操作</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @regulation_masters.each do |regulation_master| %>
      <tr>
        <td><%= regulation_master.code %></td>
        <td><%= regulation_master.name %></td>
        <td>
          <%= link_to '', regulation_master, class: "mdi-action-info-outline" %>
          <%= link_to '', edit_regulation_master_path(regulation_master), class: "mdi-editor-mode-edit" %>
          <%= link_to '', regulation_master, method: :delete, data: { confirm: '本当に消しますか？' }, class: "mdi-action-delete" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<p><%= paginate @regulation_masters %></p>

app/views/regulation_masters/new.html.erb
<h1>New Regulation Master</h1>

<%= render 'form' %>

<%= link_to 'Back', regulation_masters_path %>

app/views/regulation_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @regulation_master.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @regulation_master.name %>
</p>

<%= link_to 'Edit', edit_regulation_master_path(@regulation_master) %> |
<%= link_to 'Back', regulation_masters_path %>