config/routes.rb
Rails.application.routes.draw do

  root :to => 'pharmaceutical_masters#index'
  resources :pharmaceutical_masters do
    collection do
      post :integrate
      get :export_csv
      delete :delete_all
    end
  end
  resources :regulation_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :efficacy_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :gs1_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :hot_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :price_masters do
    collection do
      post :input
      delete :delete_all
    end
  end

end

app/models/pharmaceutical_master.rb
class PharmaceuticalMaster < ActiveRecord::Base
  # self.primary_key = "a"

  def self.integrate
    PharmaceuticalMaster.transaction do
      delete_all
      imported_num = 0
      pharmaceuticals_list = []

      # LEFT OUTER JOINするため、HOTマスタを軸にeager_loadを使用(本来、PRICEマスタを右外部か完全結合したい)
      pharmaceuticals_masters = HotMaster.eager_load(:price_master, :gs1_master)
      pharmaceuticals_masters.each do |pharmaceutical_master|
        pharmaceutical = new
        pharmaceutical.attributes= {
          a: pharmaceutical_master.a,
          b: pharmaceutical_master.f,
          c: pharmaceutical_master.g,
          d: pharmaceutical_master.i,
          e: pharmaceutical_master.ab,
          f: pharmaceutical_master.ag,
          aa: pharmaceutical_master.ba,
          ab: pharmaceutical_master.bb
        }

        if pharmaceutical_master.price_master.present?
          regulation_code = pharmaceutical_master.price_master.ad
          efficacy_code = pharmaceutical_master.g[0, 3]
          pharmaceutical.attributes= {
            g: pharmaceutical_master.price_master.ab,
            h: regulation_code,
            i: RegulationMaster.find_by(code: regulation_code).name,
            j: pharmaceutical_master.price_master.ag,
            ac: efficacy_code,
            ad: EfficacyMaster.find_by(code: efficacy_code).name
          }
        end

        if pharmaceutical_master.gs1_master.present?
          pharmaceutical.attributes= {
            ae: pharmaceutical_master.gs1_master.bj,
            af: pharmaceutical_master.gs1_master.cc,
            ag: pharmaceutical_master.gs1_master.cd
          }
        end

        pharmaceuticals_list << pharmaceutical
        imported_num += 1
      end
      PharmaceuticalMaster.import pharmaceuticals_list
      imported_num
    end
  rescue => e
    p  e.message
  end

  def self.to_csv
    headers = %w(基準番号（ＨＯＴコード） ＪＡＮコード 薬価基準収載医薬品コード レセプト電算処理システムコード（１） 販売名 包装単位単位 新又は現金額 麻薬・毒薬・覚せい剤原料・向精神薬 規制分類名 後発品 製造会社 販売会社 薬効コード 薬効分類名 調剤包装単位コード 販売包装単位コード 元梱包装単位コード)
    csv_data = CSV.generate(headers: headers, write_headers: true, force_quotes: true) do |csv|
      all.each do |row|
        # csv << row.attributes.values_at(*self.column_names)
        csv << row.attributes.values_at("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "aa", "ab", "ac", "ad", "ae", "af", "ag")
      end
    end
    csv_data.encode(Encoding::UTF_8)
  end
end

app/controllers/pharmaceutical_masters_controller.rb
class PharmaceuticalMastersController < ApplicationController
  before_action :set_pharmaceutical_master, only: [:show, :edit, :update, :destroy]

  def integrate
    num = PharmaceuticalMaster.integrate
    redirect_to(pharmaceutical_masters_url, notice: "#{num.to_s}" + INPUT_NOTICE)
  end

  def export_csv
    @pharmaceutical_masters = PharmaceuticalMaster.all
    send_data @pharmaceutical_masters.to_csv, filename: "医薬品マスタ_#{Time.current.strftime('%Y%m%d')}.csv"
  end

  def delete_all
    PharmaceuticalMaster.delete_all
    respond_to do |format|
      format.html { redirect_to pharmaceutical_masters_url, notice: DELETE_ALL_NOTICE }
      format.json { head :no_content }
    end
  end

  # GET /pharmaceutical_masters
  # GET /pharmaceutical_masters.json
  def index
    @pharmaceutical_masters = PharmaceuticalMaster.page(params[:page])
    # @pharmaceutical_masters = PharmaceuticalMaster.all
  end

  # GET /pharmaceutical_masters/1
  # GET /pharmaceutical_masters/1.json
  def show
  end

  # GET /pharmaceutical_masters/new
  def new
    @pharmaceutical_master = PharmaceuticalMaster.new
  end

  # GET /pharmaceutical_masters/1/edit
  def edit
  end

  # POST /pharmaceutical_masters
  # POST /pharmaceutical_masters.json
  def create
    @pharmaceutical_master = PharmaceuticalMaster.new(pharmaceutical_master_params)

    respond_to do |format|
      if @pharmaceutical_master.save
        format.html { redirect_to @pharmaceutical_master, notice: CREATE_NOTICE }
        format.json { render :show, status: :created, location: @pharmaceutical_master }
      else
        format.html { render :new }
        format.json { render json: @pharmaceutical_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharmaceutical_masters/1
  # PATCH/PUT /pharmaceutical_masters/1.json
  def update
    respond_to do |format|
      if @pharmaceutical_master.update(pharmaceutical_master_params)
        format.html { redirect_to @pharmaceutical_master, notice: UPDATE_NOTICE }
        format.json { render :show, status: :ok, location: @pharmaceutical_master }
      else
        format.html { render :edit }
        format.json { render json: @pharmaceutical_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharmaceutical_masters/1
  # DELETE /pharmaceutical_masters/1.json
  def destroy
    @pharmaceutical_master.destroy
    respond_to do |format|
      format.html { redirect_to pharmaceutical_masters_url, notice: DELETE_NOTICE }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmaceutical_master
      @pharmaceutical_master = PharmaceuticalMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharmaceutical_master_params
      params.require(:pharmaceutical_master).permit(:a, :b, :c, :d, :e, :f, :g, :h, :i, :j, :aa, :ab, :ac, :ad, :ae, :af, :ag)
    end
end

app/helpers/pharmaceutical_masters_helper.rb
module PharmaceuticalMastersHelper
end

app/views/pharmaceutical_masters/_form.html.erb
<%= form_for(@pharmaceutical_master) do |f| %>
  <% if @pharmaceutical_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pharmaceutical_master.errors.count, "error") %> prohibited this pharmaceutical_master from being saved:</h2>

      <ul>
      <% @pharmaceutical_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a %><br>
    <%= f.text_field :a %>
  </div>
  <div class="field">
    <%= f.label :b %><br>
    <%= f.text_field :b %>
  </div>
  <div class="field">
    <%= f.label :c %><br>
    <%= f.text_field :c %>
  </div>
  <div class="field">
    <%= f.label :d %><br>
    <%= f.text_field :d %>
  </div>
  <div class="field">
    <%= f.label :e %><br>
    <%= f.text_field :e %>
  </div>
  <div class="field">
    <%= f.label :f %><br>
    <%= f.text_field :f %>
  </div>
  <div class="field">
    <%= f.label :g %><br>
    <%= f.text_field :g %>
  </div>
  <div class="field">
    <%= f.label :h %><br>
    <%= f.text_field :h %>
  </div>
  <div class="field">
    <%= f.label :i %><br>
    <%= f.text_field :i %>
  </div>
  <div class="field">
    <%= f.label :j %><br>
    <%= f.text_field :j %>
  </div>
  <div class="field">
    <%= f.label :aa %><br>
    <%= f.text_field :aa %>
  </div>
  <div class="field">
    <%= f.label :ab %><br>
    <%= f.text_field :ab %>
  </div>
  <div class="field">
    <%= f.label :ac %><br>
    <%= f.text_field :ac %>
  </div>
  <div class="field">
    <%= f.label :ad %><br>
    <%= f.text_field :ad %>
  </div>
  <div class="field">
    <%= f.label :ae %><br>
    <%= f.text_field :ae %>
  </div>
  <div class="field">
    <%= f.label :af %><br>
    <%= f.text_field :af %>
  </div>
  <div class="field">
    <%= f.label :ag %><br>
    <%= f.text_field :ag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pharmaceutical_masters/edit.html.erb
<h1>Editing Pharmaceutical Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @pharmaceutical_master %> |
<%= link_to 'Back', pharmaceutical_masters_path %>

app/views/pharmaceutical_masters/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Pharmaceutical Masters</h1>
    <p>This is 医薬品マスタ</p>
    <p>いくつかのマスタを統合して医薬品マスタを作成＆出力</p>
    <p class="text-danger"><strong><%= flash[:alert] %></strong></p>
    <p class="text-success"><strong><%= flash[:notice] %></strong></p>

    <div class="container">
      <p>
        <%= link_to 'データ統合', integrate_pharmaceutical_masters_path, :method => :post,
                    class: "btn btn-primary btn-raised" %>
        <%= link_to 'CSV出力', export_csv_pharmaceutical_masters_path,
                    class: "btn btn-primary btn-raised"  %>
        <%= link_to '新規登録', new_pharmaceutical_master_path,
                    class: "btn btn-primary btn-raised"  %>
        <%= link_to '全削除', delete_all_pharmaceutical_masters_path, :method => :delete,
                    data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-raised"  %>
      </p>
    </div>
  </div>
</div>

<p><%= page_entries_info @pharmaceutical_masters %></p>
<p><%= paginate @pharmaceutical_masters %></p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>基準番号（ＨＯＴコード）</th>
      <th>ＪＡＮコード</th>
      <th>薬価基準収載医薬品コード</th>
      <th>レセプト電算処理システムコード（１）</th>
      <th>販売名</th>
      <th>包装単位単位</th>
      <th>新又は現金額</th>
      <th>1麻薬,2毒薬,3覚せい剤原料,5向精神薬</th>
      <th>規制分類名</th>
      <th>0先発品,1後発品</th>
      <th>製造会社</th>
      <th>販売会社</th>
      <th>薬効分類コード</th>
      <th>薬効分類名</th>
      <th>調剤包装単位コード</th>
      <th>販売包装単位コード</th>
      <th>元梱包装単位コード</th>
      <th>操作</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharmaceutical_masters.each do |pharmaceutical_master| %>
      <tr>
        <td><%= pharmaceutical_master.a %></td>
        <td><%= pharmaceutical_master.b %></td>
        <td><%= pharmaceutical_master.c %></td>
        <td><%= pharmaceutical_master.d %></td>
        <td><%= pharmaceutical_master.e %></td>
        <td><%= pharmaceutical_master.f %></td>
        <td><%= pharmaceutical_master.g %></td>
        <td><%= pharmaceutical_master.h %></td>
        <td><%= pharmaceutical_master.i %></td>
        <td><%= pharmaceutical_master.j %></td>
        <td><%= pharmaceutical_master.aa %></td>
        <td><%= pharmaceutical_master.ab %></td>
        <td><%= pharmaceutical_master.ac %></td>
        <td><%= pharmaceutical_master.ad %></td>
        <td><%= pharmaceutical_master.ae %></td>
        <td><%= pharmaceutical_master.af %></td>
        <td><%= pharmaceutical_master.ag %></td>
        <td>
          <%= link_to '', pharmaceutical_master, class: "mdi-action-info-outline" %>
          <%= link_to '', edit_pharmaceutical_master_path(pharmaceutical_master), class: "mdi-editor-mode-edit" %>
          <%= link_to '', pharmaceutical_master, method: :delete, data: { confirm: '本当に消しますか？' }, class: "mdi-action-delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @pharmaceutical_masters %>

app/views/pharmaceutical_masters/new.html.erb
<h1>New Pharmaceutical Master</h1>

<%= render 'form' %>

<%= link_to 'Back', pharmaceutical_masters_path %>

app/views/pharmaceutical_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A:</strong>
  <%= @pharmaceutical_master.a %>
</p>

<p>
  <strong>B:</strong>
  <%= @pharmaceutical_master.b %>
</p>

<p>
  <strong>C:</strong>
  <%= @pharmaceutical_master.c %>
</p>

<p>
  <strong>D:</strong>
  <%= @pharmaceutical_master.d %>
</p>

<p>
  <strong>E:</strong>
  <%= @pharmaceutical_master.e %>
</p>

<p>
  <strong>F:</strong>
  <%= @pharmaceutical_master.f %>
</p>

<p>
  <strong>G:</strong>
  <%= @pharmaceutical_master.g %>
</p>

<p>
  <strong>H:</strong>
  <%= @pharmaceutical_master.h %>
</p>

<p>
  <strong>I:</strong>
  <%= @pharmaceutical_master.i %>
</p>

<p>
  <strong>J:</strong>
  <%= @pharmaceutical_master.j %>
</p>

<p>
  <strong>Aa:</strong>
  <%= @pharmaceutical_master.aa %>
</p>

<p>
  <strong>Ab:</strong>
  <%= @pharmaceutical_master.ab %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @pharmaceutical_master.ac %>
</p>

<p>
  <strong>Ad:</strong>
  <%= @pharmaceutical_master.ad %>
</p>

<p>
  <strong>Ae:</strong>
  <%= @pharmaceutical_master.ae %>
</p>

<p>
  <strong>Af:</strong>
  <%= @pharmaceutical_master.af %>
</p>

<p>
  <strong>Ag:</strong>
  <%= @pharmaceutical_master.ag %>
</p>

<%= link_to 'Edit', edit_pharmaceutical_master_path(@pharmaceutical_master) %> |
<%= link_to 'Back', pharmaceutical_masters_path %>