config/routes.rb
Rails.application.routes.draw do

  root :to => 'pharmaceutical_masters#index'
  resources :pharmaceutical_masters do
    collection do
      post :integrate
      get :export_csv
      delete :delete_all
    end
  end
  resources :regulation_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :efficacy_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :gs1_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :hot_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :price_masters do
    collection do
      post :input
      delete :delete_all
    end
  end

end

app/models/price_master.rb
require 'csv'
class PriceMaster < ActiveRecord::Base
  # self.primary_key = "c"
  has_many :hot_masters, :primary_key => "c", :foreign_key => "i"
  belongs_to :regulation_master, :foreign_key => "ad", :primary_key => "code"

  def self.input(file)
    PriceMaster.transaction do
      delete_all
      imported_num = 0
      price_master_list = []

      open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
        csv = CSV.new(f, :headers => :first_row)
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          price_master = new
          price_master.attributes = table.to_hash.slice(
              *table.to_hash.except(:a, :b, :c, :d, :e, :f, :g, :h, :i, :j, :aa, :ab, :ac, :ad, :ae, :af, :ag, :ah, :ai, :aj, :ba, :bb, :bc, :bd, :be, :bf, :bg, :bh, :bi, :bj, :ca, :cb, :cc, :cd, :ce, :created_at, :updated_at).keys)

          if price_master.valid?
            price_master_list << price_master
            imported_num += 1
          end
        end
      end
      PriceMaster.import price_master_list
      imported_num
    end
  rescue => e
    p  e.message
  end

end

app/controllers/price_masters_controller.rb
class PriceMastersController < ApplicationController
  before_action :set_price_master, only: [:show, :edit, :update, :destroy]

  def input
    if params[:csv_file].blank?
      redirect_to(price_masters_url, alert: INPUT_BLANK_ALERT)
    elsif params[:csv_file].original_filename.eql?('price_master.csv')
      num = PriceMaster.input(params[:csv_file])
      redirect_to(price_masters_url, notice: "#{num.to_s}" + INPUT_NOTICE)
    else
      redirect_to(price_masters_url, alert: INPUT_DIFFERENT_ALERT)
    end
  end

  def delete_all
    PriceMaster.delete_all
    respond_to do |format|
      format.html { redirect_to price_masters_url, notice: DELETE_ALL_NOTICE }
      format.json { head :no_content }
    end
  end


  # GET /price_masters
  # GET /price_masters.json
  def index
    @price_masters = PriceMaster.page(params[:page])
    # @price_masters = PriceMaster.all
  end

  # GET /price_masters/1
  # GET /price_masters/1.json
  def show
  end

  # GET /price_masters/new
  def new
    @price_master = PriceMaster.new
  end

  # GET /price_masters/1/edit
  def edit
  end

  # POST /price_masters
  # POST /price_masters.json
  def create
    @price_master = PriceMaster.new(price_master_params)

    respond_to do |format|
      if @price_master.save
        format.html { redirect_to @price_master, notice: CREATE_NOTICE }
        format.json { render :show, status: :created, location: @price_master }
      else
        format.html { render :new }
        format.json { render json: @price_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_masters/1
  # PATCH/PUT /price_masters/1.json
  def update
    respond_to do |format|
      if @price_master.update(price_master_params)
        format.html { redirect_to @price_master, notice: UPDATE_NOTICE }
        format.json { render :show, status: :ok, location: @price_master }
      else
        format.html { render :edit }
        format.json { render json: @price_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_masters/1
  # DELETE /price_masters/1.json
  def destroy
    @price_master.destroy
    respond_to do |format|
      format.html { redirect_to price_masters_url, notice: DELETE_NOTICE }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_master
      @price_master = PriceMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_master_params
      params.require(:price_master).permit(:a, :b, :c, :d, :e, :f, :g, :h, :i, :j, :aa, :ab, :ac, :ad, :ae, :af, :ag, :ah, :ai, :aj, :ba, :bb, :bc, :bd, :be, :bf, :bg, :bh, :bi, :bj, :ca, :cb, :cc, :cd, :ce)
    end
end

app/helpers/price_masters_helper.rb
module PriceMastersHelper
end

app/views/price_masters/_form.html.erb
<%= form_for(@price_master) do |f| %>
  <% if @price_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price_master.errors.count, "error") %> prohibited this price_master from being saved:</h2>

      <ul>
      <% @price_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a %><br>
    <%= f.text_field :a %>
  </div>
  <div class="field">
    <%= f.label :b %><br>
    <%= f.text_field :b %>
  </div>
  <div class="field">
    <%= f.label :c %><br>
    <%= f.text_field :c %>
  </div>
  <div class="field">
    <%= f.label :d %><br>
    <%= f.text_field :d %>
  </div>
  <div class="field">
    <%= f.label :e %><br>
    <%= f.text_field :e %>
  </div>
  <div class="field">
    <%= f.label :f %><br>
    <%= f.text_field :f %>
  </div>
  <div class="field">
    <%= f.label :g %><br>
    <%= f.text_field :g %>
  </div>
  <div class="field">
    <%= f.label :h %><br>
    <%= f.text_field :h %>
  </div>
  <div class="field">
    <%= f.label :i %><br>
    <%= f.text_field :i %>
  </div>
  <div class="field">
    <%= f.label :j %><br>
    <%= f.text_field :j %>
  </div>
  <div class="field">
    <%= f.label :aa %><br>
    <%= f.text_field :aa %>
  </div>
  <div class="field">
    <%= f.label :ab %><br>
    <%= f.text_field :ab %>
  </div>
  <div class="field">
    <%= f.label :ac %><br>
    <%= f.text_field :ac %>
  </div>
  <div class="field">
    <%= f.label :ad %><br>
    <%= f.text_field :ad %>
  </div>
  <div class="field">
    <%= f.label :ae %><br>
    <%= f.text_field :ae %>
  </div>
  <div class="field">
    <%= f.label :af %><br>
    <%= f.text_field :af %>
  </div>
  <div class="field">
    <%= f.label :ag %><br>
    <%= f.text_field :ag %>
  </div>
  <div class="field">
    <%= f.label :ah %><br>
    <%= f.text_field :ah %>
  </div>
  <div class="field">
    <%= f.label :ai %><br>
    <%= f.text_field :ai %>
  </div>
  <div class="field">
    <%= f.label :aj %><br>
    <%= f.text_field :aj %>
  </div>
  <div class="field">
    <%= f.label :ba %><br>
    <%= f.text_field :ba %>
  </div>
  <div class="field">
    <%= f.label :bb %><br>
    <%= f.text_field :bb %>
  </div>
  <div class="field">
    <%= f.label :bc %><br>
    <%= f.text_field :bc %>
  </div>
  <div class="field">
    <%= f.label :bd %><br>
    <%= f.text_field :bd %>
  </div>
  <div class="field">
    <%= f.label :be %><br>
    <%= f.text_field :be %>
  </div>
  <div class="field">
    <%= f.label :bf %><br>
    <%= f.text_field :bf %>
  </div>
  <div class="field">
    <%= f.label :bg %><br>
    <%= f.text_field :bg %>
  </div>
  <div class="field">
    <%= f.label :bh %><br>
    <%= f.text_field :bh %>
  </div>
  <div class="field">
    <%= f.label :bi %><br>
    <%= f.text_field :bi %>
  </div>
  <div class="field">
    <%= f.label :bj %><br>
    <%= f.text_field :bj %>
  </div>
  <div class="field">
    <%= f.label :ca %><br>
    <%= f.text_field :ca %>
  </div>
  <div class="field">
    <%= f.label :cb %><br>
    <%= f.text_field :cb %>
  </div>
  <div class="field">
    <%= f.label :cc %><br>
    <%= f.text_field :cc %>
  </div>
  <div class="field">
    <%= f.label :cd %><br>
    <%= f.text_field :cd %>
  </div>
  <div class="field">
    <%= f.label :ce %><br>
    <%= f.text_field :ce %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/price_masters/edit.html.erb
<h1>Editing Price Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @price_master %> |
<%= link_to 'Back', price_masters_path %>

app/views/price_masters/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Price Masters</h1>
    <p>This is 薬価マスタ</p>
    <p>薬価マスタ：診療報酬情報提供サービス＞医薬品マスターは<u><%= link_to "こちら", "http://www.iryohoken.go.jp/shinryohoshu/downloadMenu/" %></u></p>
    <p>y.csv を price_master.csv に名前変更してください</p>

    <p class="text-danger"><strong><%= flash[:alert] %></strong></p>
    <p class="text-success"><strong><%= flash[:notice] %></strong></p>

    <div class="container">
      <p>
        <%= form_tag(input_price_masters_path, :method => :post, multipart: true) do %>
            <%= file_field_tag :csv_file %>
            <%= submit_tag "CSVインポート", :class => "btn btn-primary btn-raised" %>
        <% end %>
        <%= link_to '新規登録', new_price_master_path, class: "btn btn-primary btn-raised"  %>
        <%= link_to '全削除', delete_all_price_masters_path, :method => :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-raised"  %>
      </p>
    </div>
  </div>
</div>

<p><%= page_entries_info @price_masters %></p>
<p><%= paginate @price_masters %></p>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>変更区分</th>
    <th>マスター種別</th>
    <th>医薬品コード 医薬品名・規格名品コード</th>
    <th>医薬品コード 漢字有効桁数</th>
    <th>医薬品コード 漢字名称</th>
    <th>医薬品コード カナ有効桁数</th>
    <th>医薬品コード カナ名称</th>
    <th>単位 コード</th>
    <th>単位 漢字有効桁数</th>
    <th>単位 漢字名称</th>
    <th>新又は現金額 金額種別</th>
    <th>新又は現金額 新又は現金額</th>
    <th>予備</th>
    <th>1麻薬,2毒薬,3覚せい剤原料,5向精神薬</th>
    <th>神経破壊剤</th>
    <th>生物学的製剤</th>
    <th>0先発品,1後発品</th>
    <th>予備</th>
    <th>歯科特定薬剤</th>
    <th>造影(補助)剤</th>
    <th>注射容量</th>
    <th>収載方式等識別</th>
    <th>商品名等関連 旧額</th>
    <th>商品名等関連 旧金額種別</th>
    <th>商品名等関連 旧金額</th>
    <th>漢字名称変更区分</th>
    <th>カナ名称変更区分</th>
    <th>剤形</th>
    <th>予備</th>
    <th>変更年月日</th>
    <th>廃止年月日</th>
    <th>薬価基準コード</th>
    <th>公表順序番号</th>
    <th>経過措置年月日又は商品名医薬品コード使用期限</th>
    <th>基本漢字名称</th>
    <th>操作</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @price_masters.each do |price_master| %>
      <tr>
        <td><%= price_master.a %></td>
        <td><%= price_master.b %></td>
        <td><%= price_master.c %></td>
        <td><%= price_master.d %></td>
        <td><%= price_master.e %></td>
        <td><%= price_master.f %></td>
        <td><%= price_master.g %></td>
        <td><%= price_master.h %></td>
        <td><%= price_master.i %></td>
        <td><%= price_master.j %></td>
        <td><%= price_master.aa %></td>
        <td><%= price_master.ab %></td>
        <td><%= price_master.ac %></td>
        <td><%= price_master.ad %></td>
        <td><%= price_master.ae %></td>
        <td><%= price_master.af %></td>
        <td><%= price_master.ag %></td>
        <td><%= price_master.ah %></td>
        <td><%= price_master.ai %></td>
        <td><%= price_master.aj %></td>
        <td><%= price_master.ba %></td>
        <td><%= price_master.bb %></td>
        <td><%= price_master.bc %></td>
        <td><%= price_master.bd %></td>
        <td><%= price_master.be %></td>
        <td><%= price_master.bf %></td>
        <td><%= price_master.bg %></td>
        <td><%= price_master.bh %></td>
        <td><%= price_master.bi %></td>
        <td><%= price_master.bj %></td>
        <td><%= price_master.ca %></td>
        <td><%= price_master.cb %></td>
        <td><%= price_master.cc %></td>
        <td><%= price_master.cd %></td>
        <td><%= price_master.ce %></td>
        <td>
          <%= link_to '', price_master, class: "mdi-action-info-outline" %>
          <%= link_to '', edit_price_master_path(price_master), class: "mdi-editor-mode-edit" %>
          <%= link_to '', price_master, method: :delete, data: { confirm: '本当に消しますか？' }, class: "mdi-action-delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @price_masters %>

app/views/price_masters/new.html.erb
<h1>New Price Master</h1>

<%= render 'form' %>

<%= link_to 'Back', price_masters_path %>

app/views/price_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A:</strong>
  <%= @price_master.a %>
</p>

<p>
  <strong>B:</strong>
  <%= @price_master.b %>
</p>

<p>
  <strong>C:</strong>
  <%= @price_master.c %>
</p>

<p>
  <strong>D:</strong>
  <%= @price_master.d %>
</p>

<p>
  <strong>E:</strong>
  <%= @price_master.e %>
</p>

<p>
  <strong>F:</strong>
  <%= @price_master.f %>
</p>

<p>
  <strong>G:</strong>
  <%= @price_master.g %>
</p>

<p>
  <strong>H:</strong>
  <%= @price_master.h %>
</p>

<p>
  <strong>I:</strong>
  <%= @price_master.i %>
</p>

<p>
  <strong>J:</strong>
  <%= @price_master.j %>
</p>

<p>
  <strong>Aa:</strong>
  <%= @price_master.aa %>
</p>

<p>
  <strong>Ab:</strong>
  <%= @price_master.ab %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @price_master.ac %>
</p>

<p>
  <strong>Ad:</strong>
  <%= @price_master.ad %>
</p>

<p>
  <strong>Ae:</strong>
  <%= @price_master.ae %>
</p>

<p>
  <strong>Af:</strong>
  <%= @price_master.af %>
</p>

<p>
  <strong>Ag:</strong>
  <%= @price_master.ag %>
</p>

<p>
  <strong>Ah:</strong>
  <%= @price_master.ah %>
</p>

<p>
  <strong>Ai:</strong>
  <%= @price_master.ai %>
</p>

<p>
  <strong>Aj:</strong>
  <%= @price_master.aj %>
</p>

<p>
  <strong>Ba:</strong>
  <%= @price_master.ba %>
</p>

<p>
  <strong>Bb:</strong>
  <%= @price_master.bb %>
</p>

<p>
  <strong>Bc:</strong>
  <%= @price_master.bc %>
</p>

<p>
  <strong>Bd:</strong>
  <%= @price_master.bd %>
</p>

<p>
  <strong>Be:</strong>
  <%= @price_master.be %>
</p>

<p>
  <strong>Bf:</strong>
  <%= @price_master.bf %>
</p>

<p>
  <strong>Bg:</strong>
  <%= @price_master.bg %>
</p>

<p>
  <strong>Bh:</strong>
  <%= @price_master.bh %>
</p>

<p>
  <strong>Bi:</strong>
  <%= @price_master.bi %>
</p>

<p>
  <strong>Bj:</strong>
  <%= @price_master.bj %>
</p>

<p>
  <strong>Ca:</strong>
  <%= @price_master.ca %>
</p>

<p>
  <strong>Cb:</strong>
  <%= @price_master.cb %>
</p>

<p>
  <strong>Cc:</strong>
  <%= @price_master.cc %>
</p>

<p>
  <strong>Cd:</strong>
  <%= @price_master.cd %>
</p>

<p>
  <strong>Ce:</strong>
  <%= @price_master.ce %>
</p>

<%= link_to 'Edit', edit_price_master_path(@price_master) %> |
<%= link_to 'Back', price_masters_path %>