config/routes.rb
Rails.application.routes.draw do

  root :to => 'pharmaceutical_masters#index'
  resources :pharmaceutical_masters do
    collection do
      post :integrate
      get :export_csv
      delete :delete_all
    end
  end
  resources :regulation_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :efficacy_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :gs1_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :hot_masters do
    collection do
      post :input
      delete :delete_all
    end
  end
  resources :price_masters do
    collection do
      post :input
      delete :delete_all
    end
  end

end

app/models/efficacy_master.rb
require 'csv'
class EfficacyMaster < ActiveRecord::Base
  # self.primary_key = "code"

  def self.input(file)
    EfficacyMaster.transaction do
      delete_all
      imported_num = 0
      efficacy_master_list = []

      open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
        csv = CSV.new(f, :headers => :first_row)
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          efficacy_master = new
          efficacy_master.attributes = table.to_hash.slice(
              *table.to_hash.except(:code, :name, :created_at, :updated_at).keys)

          if efficacy_master.valid?
            efficacy_master_list << efficacy_master
            imported_num += 1
          end
        end
      end
      EfficacyMaster.import efficacy_master_list

      imported_num
    end
  rescue => e
    p  e.message
  end

end

app/controllers/efficacy_masters_controller.rb
class EfficacyMastersController < ApplicationController
  before_action :set_efficacy_master, only: [:show, :edit, :update, :destroy]

  def input
    if params[:csv_file].blank?
      redirect_to(efficacy_masters_url, alert: INPUT_BLANK_ALERT)
    elsif params[:csv_file].original_filename.eql?('efficacy_master.csv')
      num = EfficacyMaster.input(params[:csv_file])
      redirect_to(efficacy_masters_url, notice: "#{num.to_s}" + INPUT_NOTICE)
    else
      redirect_to(efficacy_masters_url, alert: INPUT_DIFFERENT_ALERT)
    end
  end

  def delete_all
    EfficacyMaster.delete_all
    respond_to do |format|
      format.html { redirect_to efficacy_masters_url, notice: DELETE_ALL_NOTICE }
      format.json { head :no_content }
    end
  end

  # GET /efficacy_masters
  # GET /efficacy_masters.json
  def index
    @efficacy_masters = EfficacyMaster.page(params[:page])
    # @efficacy_masters = EfficacyMaster.all
  end

  # GET /efficacy_masters/1
  # GET /efficacy_masters/1.json
  def show
  end

  # GET /efficacy_masters/new
  def new
    @efficacy_master = EfficacyMaster.new
  end

  # GET /efficacy_masters/1/edit
  def edit
  end

  # POST /efficacy_masters
  # POST /efficacy_masters.json
  def create
    @efficacy_master = EfficacyMaster.new(efficacy_master_params)

    respond_to do |format|
      if @efficacy_master.save
        format.html { redirect_to @efficacy_master, notice: CREATE_NOTICE }
        format.json { render :show, status: :created, location: @efficacy_master }
      else
        format.html { render :new }
        format.json { render json: @efficacy_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /efficacy_masters/1
  # PATCH/PUT /efficacy_masters/1.json
  def update
    respond_to do |format|
      if @efficacy_master.update(efficacy_master_params)
        format.html { redirect_to @efficacy_master, notice: UPDATE_NOTICE }
        format.json { render :show, status: :ok, location: @efficacy_master }
      else
        format.html { render :edit }
        format.json { render json: @efficacy_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /efficacy_masters/1
  # DELETE /efficacy_masters/1.json
  def destroy
    @efficacy_master.destroy
    respond_to do |format|
      format.html { redirect_to efficacy_masters_url, notice: DELETE_NOTICE }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_efficacy_master
      @efficacy_master = EfficacyMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def efficacy_master_params
      params.require(:efficacy_master).permit(:code, :name)
    end
end

app/helpers/efficacy_masters_helper.rb
module EfficacyMastersHelper
end

app/views/efficacy_masters/_form.html.erb
<%= form_for(@efficacy_master) do |f| %>
  <% if @efficacy_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@efficacy_master.errors.count, "error") %> prohibited this efficacy_master from being saved:</h2>

      <ul>
      <% @efficacy_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/efficacy_masters/edit.html.erb
<h1>Editing Efficacy Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @efficacy_master %> |
<%= link_to 'Back', efficacy_masters_path %>

app/views/efficacy_masters/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Efficacy Masters</h1>
    <p>This is 薬効分類マスタ</p>
    <p>薬効分類表は<u><%= link_to "こちら", "http://www.mhlw.go.jp/shingi/2009/11/dl/s1106-11v.pdf" %></u></p>
    <p>s1106-11v.pdf を efficacy_master.csv に名前変更してください</p>

    <p class="text-danger"><strong><%= flash[:alert] %></strong></p>
    <p class="text-success"><strong><%= flash[:notice] %></strong></p>

    <div class="container">
      <p>
        <%= form_tag(input_efficacy_masters_path, :method => :post, multipart: true) do %>
          <%= file_field_tag :csv_file %>
          <%= submit_tag "CSVインポート", :class => "btn btn-primary btn-raised" %>
        <% end %>
        <%= link_to '新規登録', new_efficacy_master_path, class: "btn btn-primary btn-raised"  %>
        <%= link_to '全削除', delete_all_efficacy_masters_path, :method => :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-raised"  %>
      </p>
    </div>
  </div>
</div>

<p><%= page_entries_info @efficacy_masters %></p>
<p><%= paginate @efficacy_masters %></p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>薬効分類コード</th>
      <th>薬効分類名</th>
      <th>操作</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @efficacy_masters.each do |efficacy_master| %>
      <tr>
        <td><%= efficacy_master.code %></td>
        <td><%= efficacy_master.name %></td>
        <td>
          <%= link_to '', efficacy_master, class: "mdi-action-info-outline" %>
          <%= link_to '', edit_efficacy_master_path(efficacy_master), class: "mdi-editor-mode-edit" %>
          <%= link_to '', efficacy_master, method: :delete, data: { confirm: '本当に消しますか？' }, class: "mdi-action-delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= paginate @efficacy_masters %></p>

app/views/efficacy_masters/new.html.erb
<h1>New Efficacy Master</h1>

<%= render 'form' %>

<%= link_to 'Back', efficacy_masters_path %>

app/views/efficacy_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @efficacy_master.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @efficacy_master.name %>
</p>

<%= link_to 'Edit', edit_efficacy_master_path(@efficacy_master) %> |
<%= link_to 'Back', efficacy_masters_path %>